### ISSUE TITLE
Can you add somewhere what version of Django this works with ?

### ISSUE THREAD

**Issue by dhivyasa** [garmoncheg/django-log-file-viewer#1]
I see following template error with Django 1.6. Looks like adminmeadia tag is no longer supported.

Exception Type: TemplateSyntaxError
Exception Value:  
'adminmedia' is not a valid tag library: Template library adminmedia not found, tried django.templatetags.adminmedia,django.contrib.admin.templatetags.adminmedia,django.contrib.staticfiles.templatetags.adminmedia

**Comment by garmoncheg** [comment]
yes I need to fix that. I'll do in couple of days. It works with 1.6.2 (the latest currently)
